### ISSUE TITLE
LIDAR Genome Design

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/feagi-core#1]
Develop the needed genes within genome to handle LIDAR data.

**Comment by erm156** [comment]
I am fairly confused about how to implement this and am just going to drop some questions/thoughts here:

- assuming the LIDAR data provides us with range value(s)

- it seems like having several layers of neurons with different sensitivities to various ranges is a general approach (if range data value falls within specific range, add that layer's neuron IDs to fire candidate list)

- how many layers? which layers? how many cells per layer? how are all of the initial blueprint parameter values determined?

- can I use the existing MNIST static genome as a framework for the LIDAR genome? or are they too unrelated?

**Comment by m-nadji-tehrani** [comment]
Great thoughts and questions. 

We can simply create a single cortical area with a single layer but give it enough depth to let us break it down into virtual layers through the block definition in Z dimension. For example you can define a cortical layer for LIDAR IPU with dimensions of 100x100x100 and can have the block boundaries as 10x10x10. In this case you have 10 z blocks to use to break down the distance into. The mapping between the LIDAR data into individual blocks would be done through the module defined under IPU/Processor for processing distance which can come from a LIDAR or a SONAR or any other time of proximity sensor. There will be another module that needs to be created under IPU/Source that receives LIDAR data and will pass the raw data to the distance processor.

**Comment by m-nadji-tehrani** [comment]
and to your question about using the MNIST static genome the answer is absolutely yes. All you need to do is to use the existing genome as is and define a new cortical area under the blueprint key to define the characteristics of the cortical region that will be processing distance data that could come from a LIDAR.

**Comment by m-nadji-tehrani** [comment]
one final note to wrap my comments; the decision to have multiple distinct cortical layers vs leveraging the Z plane with blocks comes down to the need to distinguish the property of neurons in each layer. If all the layers are going to have the same exact property and serve the same purpose we will reduce the complexity of the design by defining only one layer that can be virtually sliced into sublayers.

**Comment by erm156** [comment]
Thanks - those comments were helpful. I added a 100x100x100 LIDAR cortical area with 10x10x10 block boundaries to the existing genome file. I am not sure about which properties/neuron params (and their values) to include in this cortical area. Do I need to determine those for this specific area (or use those from another, similar area)?

**Comment by m-nadji-tehrani** [comment]
Glad to hear. We do not need to worry about the neuron parameters but we do need to wire the LIDAR region to the rest of the brain. For that you can create another cortical area called LIDAR memory and set the needed parameters in the first region so synaptogenesis can connect the two. You can look at the vision-IT and vision-memory as a example for this task.

**Comment by erm156** [comment]
I initially added the LIDAR genes to the wrong file (`static_genome.json` instead of `static_genome.py`), which is why they weren't being loaded during FEAGI initialization. Should be good now...

**Comment by erm156** [comment]
LIDAR genome is functioning properly in FEAGI, so closing this (will reopen if necessary...)
