### ISSUE TITLE
Develop Distance Processor

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/feagi-core#8]
Develop an IPU processor module capable of converting directional distance data into neuronal activities.

**Comment by m-nadji-tehrani** [comment]
Please consider the following assumptions as part of the design:
- Distance processor is responsible for translating raw data associated with distance and direction into neuronal stimulation
- Neuronal stimulation can be done by identifying a neuron id as part of lidar-ipu cortical area and adding its id to the fire-candidate-list
- raw distance data will be supplied by another module called /src/ipu/source/lidar.py that is responsible for connecting to a lidar and translating it to a standard format that can be processed by the distance processor
- Assume the following data structure format as what supplied by the LIDAR source:


`
{
00001: {
    time_stamp: standard_time_format,
    lidar_data: [
        (x_angle, z_angle, distance), 
        (x_angle, z_angle, distance), 
        (x_angle, z_angle, distance), 
        ]
    },
00002: {
    time_stamp: standard_time_format,
    lidar_data: [
        (x_angle, z_angle, distance), 
        (x_angle, z_angle, distance), 
        (x_angle, z_angle, distance), 
        ]
    }
}

`









Note: Above data structure is a suggestion. We need to evaluate if using another data structure would be beneficial.

**Comment by erm156** [comment]
From my understanding, we have a single LIDAR cortical area that is divided into 10 virtual areas. The LIDAR distance value can tell us which virtual area to target. Is there a distance threshold for LIDAR detection (i.e. an obstacle has to lie within a certain distance to trigger measurements) or are the data points continuous? Once we know the target virtual cortical area, can we use `x_angle` and `z_angle` to determine which neurons within the area are activated? I'm trying to build a more complete mental model of this so I can better understand what needs to be done via code.

**Comment by erm156** [comment]
Just to clarify - will the `lidar_data` in the proposed data structure always contain 3 tuples representing 3 spherical data points? Does this correspond to the 3 sensors on the virtual robot?

**Comment by erm156** [comment]
closed via #17
